version: "3"

services:
  server:
    build: ./server
    restart: unless-stopped
    ports:
    - "8081:8081"
    environment:
    - CORS=all
    - POSTGRES_ENDPOINT=database
    - POSTGRES_PORT=5432
    - POSTGRES_USERNAME=root
    - POSTGRES_PASSWORD=password
  
  client:
    build: ./client
    stdin_open: true
    ports:
    - "3000:3000"
    environment:
    - API_ENDPOINT=null

  database:
    image: postgres:latest
    ports:
    - "5432:5432"
    environment:
    - POSTGRES_USER=root
    - POSTGRES_PASSWORD=password
    - POSTGRES_DB=labelit