version: "3"

services:
  server:
    entrypoint: /bin/sh -c "knex migrate:latest && yarn dev"
    volumes:
    - ./server/src:/app/src
  
  client:
    environment:
    - API_ENDPOINT
    volumes:
    - ./client/src:/app/src