version: "3.8"

services:
  server:
    build: ./server
    environment:
    - POSTGRES_ENDPOINT=postgres
    - POSTGRES_USERNAME=root
    - POSTGRES_PASSWORD=password
  
  client:
    build: ./client
    environment:
    - API_ENDPOINT=null

  database:
    image: postgres:latest
    network_mode: host
    environment:
    - POSTGRES_USER=root
    - POSTGRES_PASSWORD=password
    - POSTGRES_DB=labelit